name: flutter_note_app
description: 记事本app

publish_to: 'none' 
version: 1.4.2
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mobx: ^1.0.2
  flutter_mobx: ^1.0.1
  path: ^1.6.4
  path_provider:
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  flutter_github_releases_service: ^0.4.2
  flutter_slidable: ^0.5.4
  flutter_ajanuw_router: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
